# Generated by Django 3.0.5 on 2020-05-03 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdressesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streets', models.CharField(max_length=200, verbose_name='Streets')),
                ('complement', models.CharField(max_length=100, null=True, verbose_name='Complement')),
                ('number', models.CharField(max_length=100, null=True, verbose_name='Number')),
                ('cep', models.CharField(max_length=8, null=True, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='CountysModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('foundation', models.DateField(null=True, verbose_name='Foundation')),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Countys',
            },
        ),
        migrations.CreateModel(
            name='DiseasesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
            },
        ),
        migrations.CreateModel(
            name='OriginsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('C', 'Create'), ('U', 'Update')], default='C', max_length=1, verbose_name='Kind')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Origin',
                'verbose_name_plural': 'Origins',
            },
        ),
        migrations.CreateModel(
            name='PersonsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('date_of_death', models.DateField(null=True, verbose_name='Date of death')),
                ('age', models.PositiveIntegerField(null=True, verbose_name='Age')),
                ('age_range', models.IntegerField(choices=[(-1, 'Undefined'), (0, 'up to 10 years old'), (1, 'from 10 to 19 years old'), (2, 'from 20 to 29 years old'), (3, 'from 30 to 39 years old'), (4, 'from 40 to 49 years old'), (5, 'from 50 to 59 years old'), (6, 'from 60 to 69 years old'), (7, 'from 70 to 79 years old'), (8, 'over 80 years old')], default=-1, verbose_name='Age range')),
                ('dead', models.BooleanField(default=False, verbose_name='Dead')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AdressesModel', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='StatesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('initial', models.CharField(max_length=2, unique=True, verbose_name='Initial')),
                ('region', models.IntegerField(choices=[(0, 'North'), (1, 'Northeast'), (2, 'Midwest'), (3, 'Southeast'), (4, 'South')], verbose_name='Region')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='UrlFontsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('url', models.CharField(max_length=250, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Font',
                'verbose_name_plural': 'Fonts',
            },
        ),
        migrations.CreateModel(
            name='SicksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infection_date', models.DateField(null=True, verbose_name='Infection date')),
                ('infection_identification_date', models.DateField(null=True, verbose_name='Infection identification date')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Creation date')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DiseasesModel', verbose_name='Disease')),
                ('origins', models.ManyToManyField(to='core.OriginsModel', verbose_name='Origins')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PersonsModel', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Sick',
                'verbose_name_plural': 'Sicks',
            },
        ),
        migrations.AddField(
            model_name='originsmodel',
            name='font',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UrlFontsModel', verbose_name='Font'),
        ),
        migrations.CreateModel(
            name='NeighborhoodsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CountysModel', verbose_name='County')),
            ],
            options={
                'verbose_name': 'Neighborhood',
                'verbose_name_plural': 'Neighborhood',
            },
        ),
        migrations.AddField(
            model_name='countysmodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StatesModel', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='adressesmodel',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.NeighborhoodsModel', verbose_name='Neighborhood'),
        ),
    ]
