# Generated by Django 3.0.5 on 2020-05-03 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Day')),
                ('infected_news', models.PositiveIntegerField(verbose_name='Infected News')),
                ('dead_news', models.PositiveIntegerField(verbose_name='Dead News')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DiseasesModel', verbose_name='Disease')),
            ],
            options={
                'verbose_name': 'General Data',
                'verbose_name_plural': 'Generals Data',
            },
        ),
    ]
