# Generated by Django 3.0.5 on 2020-05-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generaldatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldatamodel',
            name='dead_news',
            field=models.IntegerField(verbose_name='Dead News'),
        ),
        migrations.AlterField(
            model_name='generaldatamodel',
            name='infected_news',
            field=models.IntegerField(verbose_name='Infected News'),
        ),
    ]
